apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-app-template-3
  title: React App Template-3
  description: Create a new React app, publish it to GitHub, and deploy it to Vercel-2.
spec:
  owner: devopsfarm
  type: website

  parameters:
    - title: General Information
      required:
        - name
        - repoUrl
        - vercel_token
        - vercel_org_id
        - vercel_project_id
      properties:
        vercel_token:
          title: vercel_token
          type: string
          description: vercel_token
        vercel_org_id:
          title: vercel_org_id
          type: string
          description: vercel_org_id
        vercel_project_id:
          title: vercel_project_id
          type: string
          description: vercel_project_id
        name:
          title: Project Name
          type: string
          description: Unique name for the React app
          default: my-react-app
        repoUrl:
          title: Repository Location
          type: string
          description: GitHub repository where the app will be published
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:cookiecutter
      input:
        url: ./content/my-react
        targetPath: .
        values:
          project_name: ${{ parameters.name }}
          repoUrl: ${{ parameters.repoUrl }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
        copyWithoutRender:
          - 'node_modules/**'
          - '.github/*'

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        description: Repository for ${{ parameters.name }}
        secrets: {
              VERCEL_TOKEN: "${{ parameters.vercel_token }}",
              VERCEL_ORG_ID: "${{ parameters.vercel_org_id }}",
              VERCEL_PROJECT_ID: "${{ parameters.vercel_project_id }}"
            }

    - id: deploy-to-vercel
      name: Deploy to Vercel
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        ref: main  # or the branch you want to deploy
        workflow: './content/my-react/.github/workflows/deploy.yml'  # GitHub Action workflow file
        environment: production  # Optional, specify the environment

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - url: ${{ steps.publish.output.repositoryUrl }}
        title: Repository
      - url: ${{ steps.register.output.catalogUrl }}
        title: View in Backstage
      - url: 'https://vercel.com/dashboard'  # Link to Vercel Dashboard
